run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - gofmt
    - misspell
    - goimports
    - bodyclose
    - noctx
    - sqlclosecheck

linters-settings:
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/yohnnn/pr_reviewer_assignment_service

